import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import React, { useState } from "react";

import Navbar from '../components/Navbar'
import Sidebar from "../components/Navbar/sideBar";
import Header from '../components/_homepage/Header'


const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen(!isOpen);
  };

  return (
    <MainContainer>
      <Head>
        <title>Left Bastards</title>
        <meta name="Left Bastards" content="Generated by create next app" />
        <link rel="icon" href="/logo_gold_noTitle_06.21.png" />
      </Head>
      <Sidebar isOpen={isOpen} toggle={toggle} />
      <Navbar toggle={toggle} />
      <Header />

    </MainContainer>
  )
}

export default Home

const MainContainer = styled.div`
  min-height: 100vh;
  width: 100vw;
  display: flex;
  flex-direction: column;
  align-items: center;
`